name: ✨ 機能要望
description: 新機能・改善の提案
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: detail
    attributes:
      label: 内容
      description: 解決したい課題と提案
    validations:
      required: true
